name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  spec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crystal: [latest, nightly]
    steps:
      - uses: actions/checkout@v4
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - run: shards install
      - run: crystal spec
      - run: crystal tool format --check

  ameba:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - run: shards install
      - run: bin/ameba
